---
- hosts: one
  connection: local
  tasks:
    - name: Users
      debug:
        var: item
      with_items: "{{ users }}"
    - name: Admin user Ids
      debug:
        msg: "Admins {{admin_user_ids}} Others {{normal_user_count}}"
    - name: Assistant users
      debug:
        msg: "{{assistant_user_ids}} "
    - name: User first names
      debug:
        msg: "{{user_first_names}} "
    - name: JSON Query Admin user Ids
      debug:
        msg: "Admins {{jq_admin_user_ids}} Others {{normal_user_count}}"
    - name: JSON Query Assistant users
      debug:
        msg: "{{jq_assistant_user_ids}} "
    - name: JSON Query B users
      debug:
        msg: "{{jq_bid_user_ids}} "
